# Generated by Django 4.1.5 on 2023-01-10 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='first_to',
            new_name='best_of',
        ),
    ]
