# Generated by Django 4.1.5 on 2023-01-10 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_rename_first_to_room_best_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='challenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenger', to=settings.AUTH_USER_MODEL),
        ),
    ]
