# Generated by Django 4.1.5 on 2023-01-10 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_room_challenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='viewers',
            field=models.ManyToManyField(related_name='viewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
