# Generated by Django 4.1.5 on 2023-01-10 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_room_board_state_room_challenger_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='overall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overall', to=settings.AUTH_USER_MODEL),
        ),
    ]
