# Generated by Django 4.1.5 on 2023-01-11 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='challenger',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenger', to=settings.AUTH_USER_MODEL),
        ),
    ]
